import type { Call } from "./types";

// Seattle-area coordinates for demo
export const calls: Call[] = [
  {
    id: "1",
    numberMasked: "(206) 555-1289",
    priority: "P0",
    incidentType: "Unresponsive Person",
    incidentIcon: "",
    status: "AI → Human Takeover",
    statusDetail: "AI handling ∞ /analysis→...",
    locationLabel: "Helen Madison Park",
    address: "1600 36th Ave E, Seattle, WA 98112",
    city: "Seattle, WA",
    confidence: 95,
    inServiceArea: true,
    transcript: [
      { sender: "ai", text: "I'm at thave your name and location?", time: "17:22", callerName: "Alex" },
      { sender: "caller", text: "I'm at Helen Madison Park. There's a man lying unconscious on the ground near the ground.", time: "18:22", callerName: "Alex" },
      { sender: "ai", text: "Okay, stay with me. I'll ask a few questions.", time: "18:25" },
      { sender: "caller", text: "Sure, go ahead.", time: "18:26", callerName: "Alex" },
    ],
    summary: "Unresponsive adult male lying near playground in Helen Madison Park. Breathing but unresponsive.",
    keyFacts: [
      "Helen Madison Park, 36th Ave E",
      "Adult male, appears 50s",
      "Breathing but unresponsive",
    ],
    elapsed: "29:41",
    aiHandling: true,
    pin: { lat: 47.6375, lng: -122.2885 },
  },
  {
    id: "2",
    numberMasked: "(206) 555-1755",
    priority: "P1",
    incidentType: "Traffic Accident",
    incidentIcon: "",
    status: "In progress",
    locationLabel: "Aurora Bridge",
    address: "Aurora Ave N, Seattle, WA 98103",
    city: "Seattle, WA",
    confidence: 87,
    inServiceArea: true,
    transcript: [
      { sender: "caller", text: "There's been a car crash on Aurora Bridge, two vehicles involved.", time: "16:50", callerName: "Maria" },
      { sender: "ai", text: "Are there any injuries visible?", time: "16:51" },
      { sender: "caller", text: "Yes, one driver appears to be injured.", time: "16:52", callerName: "Maria" },
    ],
    summary: "Two-vehicle collision on Aurora Bridge. One driver with apparent injuries. Traffic blocked northbound.",
    keyFacts: [
      "Aurora Bridge, northbound lanes",
      "Two vehicles involved",
      "One driver injured",
    ],
    elapsed: "38:73",
    aiHandling: false,
    pin: { lat: 47.6512, lng: -122.3471 },
  },
  {
    id: "3",
    numberMasked: "(206) 555-2353",
    priority: "P0",
    incidentType: "House Fire",
    incidentIcon: "",
    status: "Dispatched",
    locationLabel: "Ravenna neighborhood",
    address: "6500 25th Ave NE, Seattle, WA 98115",
    city: "Seattle, WA",
    confidence: 92,
    inServiceArea: true,
    transcript: [
      { sender: "caller", text: "My neighbor's house is on fire! I can see flames from the second floor!", time: "16:30", callerName: "James" },
      { sender: "ai", text: "Is anyone still inside the building?", time: "16:31" },
      { sender: "caller", text: "I don't know, I haven't seen them come out.", time: "16:32", callerName: "James" },
    ],
    summary: "Residential fire reported at Ravenna neighborhood. Flames visible from second floor. Unknown if occupants are inside.",
    keyFacts: [
      "6500 25th Ave NE",
      "Second floor flames visible",
      "Occupant status unknown",
    ],
    elapsed: "28:19",
    aiHandling: false,
    pin: { lat: 47.6742, lng: -122.3008 },
  },
  {
    id: "4",
    numberMasked: "(206) 555-1369",
    priority: "P3",
    incidentType: "Noise Complaint",
    incidentIcon: "",
    status: "AI handling",
    locationLabel: "Capitol Hill",
    address: "1200 E Pike St, Seattle, WA 98122",
    city: "Seattle, WA",
    confidence: 78,
    inServiceArea: true,
    transcript: [
      { sender: "caller", text: "There's extremely loud music coming from the apartment next door.", time: "15:45", callerName: "Pat" },
      { sender: "ai", text: "How long has this been going on?", time: "15:46" },
    ],
    summary: "Noise complaint about loud music at Capitol Hill apartment.",
    keyFacts: [
      "1200 E Pike St",
      "Loud music from adjacent unit",
      "Ongoing for 2+ hours",
    ],
    elapsed: "10:10",
    aiHandling: true,
    pin: { lat: 47.6145, lng: -122.3178 },
  },
  {
    id: "5",
    numberMasked: "(206) 555-5553",
    priority: "P3",
    incidentType: "Police - Livelihood",
    incidentIcon: "",
    status: "Queued",
    locationLabel: "University District",
    address: "4500 University Way NE, Seattle, WA 98105",
    city: "Seattle, WA",
    confidence: 65,
    inServiceArea: true,
    transcript: [
      { sender: "caller", text: "Someone broke into my car overnight and stole items.", time: "14:20", callerName: "Sam" },
    ],
    summary: "Vehicle break-in reported at University District. Items stolen overnight.",
    keyFacts: [
      "4500 University Way NE",
      "Vehicle break-in",
      "Occurred overnight",
    ],
    elapsed: "02:25",
    aiHandling: false,
    pin: { lat: 47.6615, lng: -122.3128 },
  },
  {
    id: "6",
    numberMasked: "(206) 555-2563",
    priority: "P2",
    incidentType: "Noise Complaint",
    incidentIcon: "",
    status: "In progress",
    locationLabel: "Ballard",
    address: "5300 Ballard Ave NW, Seattle, WA 98107",
    city: "Seattle, WA",
    confidence: 72,
    inServiceArea: true,
    transcript: [
      { sender: "caller", text: "Construction noise at 6 AM, it's a Saturday.", time: "06:02", callerName: "Lee" },
    ],
    summary: "Construction noise complaint in Ballard on weekend morning.",
    keyFacts: [
      "5300 Ballard Ave NW",
      "Construction noise",
      "Early morning Saturday",
    ],
    elapsed: "18:02",
    aiHandling: false,
    pin: { lat: 47.6685, lng: -122.3842 },
  },
  {
    id: "7",
    numberMasked: "(206) 555-3555",
    priority: "P3",
    incidentType: "Fence Fire",
    incidentIcon: "",
    status: "AI handling",
    locationLabel: "Fremont",
    address: "3600 Fremont Ave N, Seattle, WA 98103",
    city: "Seattle, WA",
    confidence: 60,
    inServiceArea: true,
    transcript: [
      { sender: "caller", text: "A fence is smoldering in the alley behind our house.", time: "16:30", callerName: "Robin" },
    ],
    summary: "Small fence fire reported in Fremont alley.",
    keyFacts: [
      "3600 Fremont Ave N",
      "Fence smoldering in alley",
      "No structure involvement",
    ],
    elapsed: "16:47",
    aiHandling: true,
    pin: { lat: 47.6518, lng: -122.3502 },
  },
  {
    id: "8",
    numberMasked: "(206) 555-3939",
    priority: "P3",
    incidentType: "Suspicious Activity",
    incidentIcon: "",
    status: "Queued",
    locationLabel: "South Lake Union",
    address: "400 Westlake Ave N, Seattle, WA 98109",
    city: "Seattle, WA",
    confidence: 55,
    inServiceArea: true,
    transcript: [
      { sender: "caller", text: "There's a suspicious person lurking around parked cars.", time: "20:30", callerName: "Kai" },
    ],
    summary: "Suspicious activity reported near parked vehicles in South Lake Union.",
    keyFacts: [
      "400 Westlake Ave N",
      "Individual checking car doors",
      "Wearing dark hoodie",
    ],
    elapsed: "33:59",
    aiHandling: false,
    pin: { lat: 47.6262, lng: -122.3385 },
  },
  {
    id: "9",
    numberMasked: "(206) 555-2956",
    priority: "P0",
    incidentType: "Suspicious Activity",
    incidentIcon: "",
    status: "AI handling",
    locationLabel: "Pioneer Square",
    address: "100 1st Ave S, Seattle, WA 98104",
    city: "Seattle, WA",
    confidence: 88,
    inServiceArea: true,
    transcript: [
      { sender: "caller", text: "There's a group of people acting aggressively near the park.", time: "21:00", callerName: "Jordan" },
      { sender: "ai", text: "Can you describe how many people are involved?", time: "21:01" },
    ],
    summary: "Group disturbance reported at Pioneer Square. Multiple individuals acting aggressively.",
    keyFacts: [
      "100 1st Ave S",
      "Group of 4-5 people",
      "Aggressive behavior near park",
    ],
    elapsed: "26:03",
    aiHandling: true,
    pin: { lat: 47.6022, lng: -122.3340 },
  },
];
